apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/part-of: youngwon-platform
spec:
  selector:
    app.kubernetes.io/name: portfolio
  ports:
    - name: http
      port: 80
      targetPort: http
