services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${CONFD_DIR}:/etc/nginx/conf.d
      - ${SSL_DIR}:/etc/nginx/ssl
    networks:
      - youngwon
    ports:
      - 80:80
      - 443:443

networks:
  youngwon:
    external: true