apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: oci-platform
  source:
    repoURL: https://github.com/yw7148/server.git
    targetRevision: HEAD
    path: apps/portfolio/overlays/prod
  destination:
    name: oci-prod
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
